menu_tree/main/urls.py
from django.urls import path
from .views import index, detail_menu, detail_submenu

app_name = 'main'

urlpatterns = [
    path('<int:menu_pk>/<int:pk>/', detail_submenu, name='detail_submenu'),
    path('<int:pk>/', detail_menu, name='detail_menu'),
    path('', index, name='index')
]

menu_tree/menu_tree/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
]

menu_tree/main/models.py
from django.db import models


class Menu(models.Model):
    menu = models.CharField(max_length=30, unique=True,
                            verbose_name='Меню')
    order = models.SmallIntegerField(default=0, db_index=True,
                                     verbose_name='порядок')

    def __str__(self):
        return self.menu

    class Meta:
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'
        ordering = ['order']


class SubMenu(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE,
                             verbose_name='Меню')
    name = models.CharField(max_length=50, unique=True,
                            verbose_name='Название', db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подменю'
        verbose_name_plural = 'Подменю'
        ordering = ['name']


class SubMenuItems(models.Model):
    submenu = models.ForeignKey(SubMenu, on_delete=models.CASCADE,
                                verbose_name='Подменю')
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name='Добавлено', db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вложения'
        verbose_name_plural = 'Вложения'
        ordering = ['-created_at']

menu_tree/main/forms.py
from django import forms
from .models import Menu, SubMenu, SubMenuItems


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('menu',)


class SubMenuForm(forms.ModelForm):
    class Meta:
        model = SubMenu
        fields = '__all__'


class SubMenuItemsForm(forms.ModelForm):
    class Meta:
        model = SubMenuItems
        fields = '__all__'

menu_tree/main/views.py
from django.shortcuts import render, get_object_or_404
from main.models import SubMenu, Menu, SubMenuItems


def index(request):
    return render(request, 'main/index.html')


def detail_menu(request, pk):
    menu = get_object_or_404(Menu, pk=pk)
    submenu = SubMenu.objects.filter(menu=pk)
    context = {'menu': menu, 'submenu': submenu}

    return render(request, 'main/detail_menu.html', context)


def detail_submenu(request, menu_pk, pk):
    submenu = get_object_or_404(SubMenu, pk=pk)
    items = SubMenuItems.objects.filter(submenu=pk)
    context = {'items': items, 'submenu': submenu}
    return render(request, 'main/detail_submenu.html', context)

menu_tree/main/templates/layout/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

.navbar {
  overflow: hidden;
  background-color: #333;
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}
</style>
</head>
<body>
<div> {% block title %}{% endblock %}</div>
<div> {% block content %}{% endblock %}</div>
</body>
</html>

menu_tree/main/templates/main/detail_menu.html
{% extends 'main/index.html' %}
{% load menu_template %}

{% block content %}
<h2>{{ menu.menu }}</h2>
<ul>
{% for obj in submenu %}
    <dl><a href="{% url 'main:detail_submenu' menu_pk=menu.pk pk=obj.pk %}">
    <h3>{{ obj.name }}</h3></a>
    {% draw_items pk=obj.pk %}</dl>
{% endfor %}
</ul>

{% endblock %}

menu_tree/main/templates/main/detail_submenu.html
{% extends 'main/index.html' %}
{% load menu_template %}

{% block content %}
<h2>{{ submenu.menu }} : <a href="#" onclick="history.go(-1)">{{ submenu.name }}</a></h2>

<ul>
{% for obj in items %}
    <dt><a href="#">
    <h3>{{ obj.title }} : {{ obj.description }}</h3></a></dt>
{% endfor %}
</ul>
{% endblock %}

menu_tree/main/templates/main/index.html
{% extends 'layout/base.html' %}
{% load menu_template %}
{% block title %}
<body style="background-color:white;">

<div class="navbar">
  <a href="{% url 'main:index' %}">Home</a>
  <div class="dropdown">
    <button class="dropbtn">Menu
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      {% draw_menu 'main_menu' %}
    </div>
  </div>
</div>
<div>
</div>
</body>
{% endblock %}

menu_tree/main/templates/main/items.html
<ul>
{% for obj in items %}
    <a href="#">
    <dt>{{ obj.title }}</dt> </a>
{% endfor %}
</ul>

menu_tree/main/templates/main/main_menu.html
{% for obj in menu %}
<a href="{% url 'main:detail_menu' pk=obj.pk %}">
    <h3>{{ obj.menu }}</h3> </a>
{% endfor %}